api:
  dashboard: true
  insecure: false

entryPoints:
  websecure:
    address: ":443"
        
providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    directory: /config
    watch: true
